// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetStore.DataAccess.Data;

#nullable disable

namespace NetStore.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250210182822_addProducts")]
    partial class addProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NetStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Grains"
                        });
                });

            modelBuilder.Entity("NetStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price2")
                        .HasColumnType("float");

                    b.Property<double>("Price3")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Organic Farms",
                            Description = "Red Delicious",
                            ListPrice = 1.5,
                            Price = 1.0,
                            Price2 = 0.75,
                            Price3 = 0.5,
                            ProductName = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Organic Farms",
                            Description = "Tangy Sweet",
                            ListPrice = 1.25,
                            Price = 1.0,
                            Price2 = 0.75,
                            Price3 = 0.5,
                            ProductName = "Orange"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Organic Farms",
                            Description = "Yellow crisp",
                            ListPrice = 1.0,
                            Price = 1.0,
                            Price2 = 0.75,
                            Price3 = 0.5,
                            ProductName = "Bell Pepper"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "The RedMill",
                            Description = "Chewy whole grain",
                            ListPrice = 1.0,
                            Price = 1.0,
                            Price2 = 0.75,
                            Price3 = 0.5,
                            ProductName = "Oatmeal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
